import { envFilePath, newsDataProvider } from './config/env.js';
import express from 'express';
import cors from 'cors';
import http from 'node:http';
import { z } from 'zod';
import XLSX from 'xlsx';
import { WebSocketServer } from 'ws';
import { DEFAULT_INPUTS } from '../shared/defaults.js';
import { runAnalysis } from './analysis/engine.js';
import { db, getJournal, saveJournal } from './db.js';
import { MarketDataService } from './providers/marketDataService.js';
import { ForexFactoryCalendarProvider, ForexFactoryNewsProvider } from './providers/forexFactoryNewsProvider.js';
import { MarketauxNewsProvider } from './providers/marketauxNewsProvider.js';
import type { NewsProvider } from './providers/newsProvider.js';
import { BiQuoteDxyProvider } from './providers/biQuoteDxyProvider.js';
import { FredFedRateProvider } from './providers/fredFedRateProvider.js';
import { TwelveDataFedRateExpectationsProvider } from './providers/fedRateExpectationsProvider.js';
import type { MarketMode, MarketTimeframe } from '../shared/types.js';

const app = express();
app.use(cors()); app.use(express.json({ limit: '4mb' }));
const savedMode=db.prepare("SELECT value FROM settings WHERE key='market_mode'").get() as {value?:string}|undefined;
const initialMode:MarketMode=(savedMode?.value??process.env.MARKET_DATA_MODE)?.toUpperCase()==='LIVE'?'LIVE':'SIMULATION';
const market=new MarketDataService(initialMode);
const newsProvider:NewsProvider=newsDataProvider==='forexfactory'?new ForexFactoryNewsProvider():new MarketauxNewsProvider();if(newsDataProvider==='marketaux'){console.info(`[MARKETAUX] NEWS_DATA_PROVIDER: ${newsDataProvider}`);console.info(`[MARKETAUX] env file path: ${envFilePath}`)}const calendarProvider=new ForexFactoryCalendarProvider();const dxyProvider=new BiQuoteDxyProvider();const fedRateProvider=new FredFedRateProvider();const fedExpectationsProvider=new TwelveDataFedRateExpectationsProvider();
app.get('/api/health', (_req, res) => res.json({ ok: true, price: market.active.getStatus(), marketMode: market.active.mode, ai: 'OFFLINE', database: 'LOCAL' }));
app.get('/api/market/price', async (_req,res)=>{try{res.json(await market.getCurrentPrice())}catch(e){res.status(503).json({error:e instanceof Error?e.message:'Market data unavailable',status:market.active.getStatus()})}});
app.get('/api/market/candles', async (req,res)=>{const timeframe=String(req.query.timeframe??'1H') as MarketTimeframe;const allowed=['5M','15M','1H','4H','1D'];if(!allowed.includes(timeframe))return res.status(400).json({error:'Unsupported timeframe'});try{res.json(await market.getCandles(timeframe,Number(req.query.count)||500,typeof req.query.before==='string'?req.query.before:undefined))}catch(e){res.status(503).json({error:e instanceof Error?e.message:'Candle data unavailable',status:market.active.getStatus()})}});
app.get('/api/market/levels', async (req,res)=>{try{res.json(await market.getLevels(String(req.query.timeframe??'1H') as MarketTimeframe))}catch(e){res.status(503).json({error:e instanceof Error?e.message:'Level data unavailable',status:market.active.getStatus()})}});
app.get('/api/market/snapshot', async (_req,res)=>res.json(await market.getSnapshot()));
app.post('/api/market/refresh',async(_req,res)=>{try{const price=await market.refreshCurrentPrice();res.json({price,status:market.active.getStatus()})}catch(e){res.status(503).json({error:e instanceof Error?e.message:'Market data unavailable',status:market.active.getStatus()})}});
app.get('/api/market/config', (_req,res)=>res.json({mode:market.active.mode,provider:market.active.source,status:market.active.getStatus(),configured:market.active.isConfigured(),environment:market.active.source==='OANDA'?(process.env.OANDA_ENVIRONMENT==='live'?'live':'practice'):'api',staleAfterMs:market.active.source==='TWELVE_DATA'?(Number(process.env.TWELVE_DATA_POLL_INTERVAL_MS)||60000)*2:Number(process.env.OANDA_STALE_AFTER_MS)||15000}));
app.get('/api/data/state',async(_req,res)=>{const [gold,dxy,currentRate,expectations,news,economicCalendar]=await Promise.all([market.getSnapshot(),dxyProvider.getSnapshot(),fedRateProvider.getSnapshot(),fedExpectationsProvider.getSnapshot(),newsProvider.getNews(),calendarProvider.getNews()]);res.json({gold,dxy,fed:{currentRate,expectations},news,economicCalendar})});
app.get('/api/news',async(_req,res)=>res.json(await newsProvider.getNews()));
app.get('/api/macro/dxy',async(req,res)=>res.json(await dxyProvider.getSnapshot(req.query.refresh==='true')));
app.get('/api/macro/dxy/candles',async(req,res)=>{const timeframe=String(req.query.timeframe??'1H') as MarketTimeframe;if(!['5M','15M','1H','4H','1D'].includes(timeframe))return res.status(400).json({error:'Unsupported timeframe'});try{res.json(await dxyProvider.getCandles(timeframe,Number(req.query.count)||500,typeof req.query.before==='string'?req.query.before:undefined))}catch(e){res.status(503).json({error:e instanceof Error?e.message:'DXY chart history unavailable'})}});
app.get('/api/macro/fed',async(req,res)=>{const force=req.query.refresh==='true';const [currentRate,expectations]=await Promise.all([fedRateProvider.getSnapshot(force),fedExpectationsProvider.getSnapshot(force)]);res.json({currentRate,expectations})});
app.post('/api/data/refresh/fred',async(_req,res)=>{const [currentRate,expectations]=await Promise.all([fedRateProvider.refresh(),fedExpectationsProvider.refresh()]);res.json({currentRate,expectations})});
app.post('/api/data/refresh/forex-factory',async(_req,res)=>res.json(await calendarProvider.refresh(true)));
app.post('/api/data/refresh/news',async(_req,res)=>res.json(await newsProvider.refresh(true)));
app.put('/api/market/config', (req,res)=>{const parsed=z.object({mode:z.enum(['SIMULATION','LIVE'])}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Mode must be SIMULATION or LIVE'});market.setMode(parsed.data.mode);db.prepare("INSERT INTO settings(key,value) VALUES('market_mode',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(parsed.data.mode);res.json({mode:market.active.mode,status:market.active.getStatus(),configured:market.active.isConfigured()})});
app.post('/api/analyze', (req, res) => {
  const parsed = z.object({ xauusd: z.number(), dxy: z.number(), us2y: z.number(), us10y: z.number(), realYield: z.number(), fedStance: z.string(), economicData: z.string(), cot: z.string(), centralBanks: z.string(), geopolitics: z.string(), newsSentiment: z.string(), technicalStructure: z.string(), liquidity: z.string(), eventRisk: z.boolean() }).safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: 'Invalid market inputs', details: parsed.error.issues });
  const analysis = runAnalysis(req.body);
  const info = db.prepare('INSERT INTO analyses(payload, created_at) VALUES (?, ?)').run(JSON.stringify(analysis), analysis.createdAt);
  res.json({ ...analysis, id: Number(info.lastInsertRowid) });
});
app.get('/api/journal', (_req, res) => res.json(getJournal()));
app.post('/api/journal', (req, res) => res.status(201).json(saveJournal(req.body)));
app.get('/api/journal/export', (_req, res) => {
  const headers = ['Date/Time','Instrument','Direction','Market Conditions','Thesis','Entry','Stop Loss','TP1','TP2','TP3','R:R','Position Size','Conviction (Low/Med/High)','Invalidation (what proves thesis wrong)','Result (Win/Loss/BE/Open)','R Multiple','What Went Right','What Went Wrong','Lesson / Adjustment'];
  const rows = getJournal().map((j:any) => [j.dateTime,j.instrument,j.direction,j.marketConditions,j.thesis,j.entry,j.stopLoss,j.tp1,j.tp2,j.tp3,j.rr,j.positionSize,j.conviction,j.invalidation,j.result,j.rMultiple,j.wentRight,j.wentWrong,j.lesson]);
  const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([headers, ...rows]), 'Trade Journal');
  const out = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
  res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').attachment('GOLD_INTEL_Trade_Journal.xlsx').send(out);
});
app.get('/api/mock/defaults', (_req, res) => res.json(DEFAULT_INPUTS));
const server=http.createServer(app);
const wss=new WebSocketServer({server,path:'/ws/market'});
wss.on('connection',socket=>{console.info(`[WS] Client connected (${wss.clients.size})`);void market.getSnapshot().then(snapshot=>socket.send(JSON.stringify({type:'snapshot',data:snapshot})));void dxyProvider.getSnapshot().then(snapshot=>socket.send(JSON.stringify({type:'dxy',data:snapshot})));const offPrice=market.subscribe(price=>{if(socket.readyState===socket.OPEN){socket.send(JSON.stringify({type:'price',data:{...price,status:market.active.getStatus()}}));console.debug(`[WS] Broadcasting XAUUSD ${price.mid}`)}});const offCandle=market.subscribeCandle((timeframe,candle)=>{if(socket.readyState===socket.OPEN)socket.send(JSON.stringify({type:'candle',data:{timeframe,candle}}))});const offDxy=dxyProvider.subscribe(snapshot=>{if(socket.readyState===socket.OPEN)socket.send(JSON.stringify({type:'dxy',data:snapshot}))});socket.on('close',()=>{offPrice();offCandle();offDxy()})});
app.get('/api/market/debug', async (_req,res)=>{if(process.env.NODE_ENV==='production')return res.status(404).end();const snapshot=await market.getSnapshot();res.json({streamStatus:market.active.getStatus(),instrument:'XAU_USD',latest:snapshot.price,webSocketClients:wss.clients.size,mode:market.active.mode,configured:market.active.isConfigured()})});
function safeRefresh(label:string,refresh:()=>Promise<unknown>){void refresh().catch(error=>console.error(`[REFRESH] ${label} failed safely:`,error instanceof Error?error.message:error))}
safeRefresh('FRED',()=>fedRateProvider.refresh());safeRefresh('Fed expectations',()=>fedExpectationsProvider.refresh());safeRefresh('Forex Factory calendar',()=>calendarProvider.refresh());safeRefresh('News',()=>newsProvider.refresh());dxyProvider.start();
const refreshTimers=[setInterval(()=>safeRefresh('DXY',()=>dxyProvider.refresh()),dxyProvider.refreshInterval),setInterval(()=>safeRefresh('FRED',()=>fedRateProvider.refresh()),fedRateProvider.refreshInterval),setInterval(()=>safeRefresh('Fed expectations',()=>fedExpectationsProvider.refresh()),fedExpectationsProvider.refreshInterval),setInterval(()=>safeRefresh('Forex Factory calendar',()=>calendarProvider.refresh()),calendarProvider.refreshInterval),setInterval(()=>safeRefresh('News',()=>newsProvider.refresh()),newsProvider.refreshInterval)];refreshTimers.forEach(timer=>timer.unref());
server.listen(4173,'127.0.0.1',()=>console.log(`GOLD INTEL API http://localhost:4173 · Market ${market.active.mode}`));
