import { useEffect, useState } from 'react';
import { Play, Save, ShieldAlert, Target } from 'lucide-react';
import { analyze, saveJournal } from '../api';
import { Card, Metric, MockBadge, PageHead } from '../components';
import { DEFAULT_INPUTS } from '../../shared/defaults';
import type { Analysis, MarketInputs } from '../../shared/types';
import { priceStatusLabel, useMarket } from '../market';
import { XauUsdChart } from '../components/XauUsdChart';
import { useCentralData } from '../data';
import { runAnalysis } from '../../server/analysis/engine';

export function Dashboard(){
  const [inputs,setInputs]=useState<MarketInputs>(()=>JSON.parse(localStorage.getItem('gold-inputs')||JSON.stringify(DEFAULT_INPUTS)));
  const [result,setResult]=useState<Analysis|null>(()=>runAnalysis(DEFAULT_INPUTS)); const [running,setRunning]=useState(false); const [saved,setSaved]=useState(false);
  const {price,snapshot}=useMarket();
  const {data}=useCentralData();const dxy=data?.dxy;const analysisDxy=dxy?.value??inputs.dxy;
  const run=async()=>{setRunning(true);setSaved(false);localStorage.setItem('gold-inputs',JSON.stringify(inputs));try{setResult(await analyze({...inputs,dxy:analysisDxy,xauusd:price?.mid??inputs.xauusd,technicalStructure:snapshot?.levels?.structure==='RANGE'?'NEUTRAL':snapshot?.levels?.structure??inputs.technicalStructure}).catch(()=>runAnalysis({...inputs,dxy:analysisDxy,xauusd:price?.mid??inputs.xauusd,technicalStructure:snapshot?.levels?.structure==='RANGE'?'NEUTRAL':snapshot?.levels?.structure??inputs.technicalStructure})))}finally{setTimeout(()=>setRunning(false),450)}};
  useEffect(()=>{if(data)void run()},[Boolean(data)]);
  const save=async()=>{if(!result)return;await saveJournal({dateTime:result.createdAt,instrument:'XAUUSD',direction:result.bias.replace('_',' '),marketConditions:`DXY ${inputs.dxy}, US10Y ${inputs.us10y}%, ${inputs.technicalStructure.toLowerCase()} structure`,thesis:result.primaryScenario,entry:result.trade?.entryLow,stopLoss:result.trade?.stop,tp1:result.trade?.tp1,tp2:result.trade?.tp2,tp3:result.trade?.tp3,rr:result.trade?.rr,positionSize:'',conviction:result.conviction>=70?'High':result.conviction>=45?'Medium':'Low',invalidation:result.invalidation,result:'Open'});setSaved(true)};
  return <div className="page"><PageHead eyebrow="GOLD INTEL / DEMO ACCOUNT" title="Gold Intelligence" sub="An explainable, evidence-weighted view of the XAUUSD environment." actions={<div className="head-actions"><span className="mockbadge"><i/>SIMULATED DATA</span><button className="primary" onClick={run}><Play size={15}/>{running?'ANALYZING…':'RUN GOLD INTEL'}</button></div>}/>
    {result&&<><div className="decision-grid"><Card className="hero"><div className="biasline"><div><small>CURRENT DECISION</small><h3 className={result.bias==='LONG'?'bull':result.bias==='SHORT'?'bear':'neutral'}>{result.bias.replace('_',' ')}</h3></div><div className="conviction"><span>{result.conviction}</span><small>/ 100<br/>CONVICTION</small></div></div><p className="lead">{result.blockers[0]||result.primaryScenario}</p><div className="scenario"><span><small>PRIMARY SCENARIO</small>{result.primaryScenario}</span><span><small>ALTERNATIVE</small>{result.alternativeScenario}</span></div><div className="herofoot"><span><Target size={15}/> Key level <b>{result.keyLevel}</b></span><span><ShieldAlert size={15}/> {result.invalidation}</span><button onClick={save} disabled={saved}><Save size={14}/>{saved?'SAVED':'SAVE TO JOURNAL'}</button></div></Card>
      <Card title="Probability Engine" meta="NORMALIZED"><div className="prob-ring" style={{'--p':`${result.bearish*3.6}deg`} as any}><div><b>{Math.max(result.bullish,result.bearish)}%</b><span>{result.bearish>result.bullish?'BEARISH':'BULLISH'}</span></div></div><div className="probs"><span><i className="bullbg" style={{width:`${result.bullish}%`}}/>Bullish <b>{result.bullish}%</b></span><span><i className="bearbg" style={{width:`${result.bearish}%`}}/>Bearish <b>{result.bearish}%</b></span><span><i className="neutralbg" style={{width:`${result.uncertain}%`}}/>Uncertain <b>{result.uncertain}%</b></span></div></Card></div>
      <div className="kpis"><div className="metric live-price"><small>XAUUSD <em>{priceStatusLabel(price,snapshot)}</em></small><strong>{price?.mid.toFixed(2)??'—'}</strong><span>{price?`Demo update ${new Date(price.receivedAt??price.timestamp).toLocaleTimeString()} · Bid ${price.bid?.toFixed(2)??'—'} · Ask ${price.ask?.toFixed(2)??'—'}`:'Demo market data loading'}</span></div><Metric label="DXY" value={dxy?.value?.toFixed(2)??'—'} sub={dxy?.value!=null?`${dxy.changePercent!=null?`${dxy.changePercent>=0?'+':''}${dxy.changePercent.toFixed(2)}% · `:''}*** · DEMO`:'DEMO DATA UNAVAILABLE'}/><Metric label="US 10Y" value={`${inputs.us10y.toFixed(2)}%`} sub="DEMO · +8bp today" tone="bear"/><Metric label="REAL YIELD" value={`${inputs.realYield.toFixed(2)}%`} sub="DEMO · Restrictive" tone="bear"/><Metric label="EFFECTIVE FED FUNDS" value={data?.fed.currentRate.rate!=null?`${data.fed.currentRate.rate.toFixed(2)}%`:'—'} sub="*** · DEMO DATA"/></div>
      <div className="content-grid"><Card><XauUsdChart defaultTimeframe="1H" defaultVisibleDays={5} compact/></Card>
      <Card title="Evidence Scoreboard" meta={`${result.evidence.length} SIGNALS`}><div className="evidence">{result.evidence.map(e=><div key={e.category}><span><b>{e.category}</b><small>{e.explanation}</small></span><em className={e.score>10?'bull':e.score<-10?'bear':'neutral'}>{e.score>0?'+':''}{e.score}</em><i><u style={{width:`${Math.abs(e.score)}%`}}/></i><small>{e.weight}%</small></div>)}</div></Card></div>
      <Card title="Mock Data Control Center" meta="DEVELOPER / DEMO"><Controls inputs={inputs} setInputs={setInputs} run={run}/></Card></>}
  </div>
}
function Controls({inputs,setInputs,run}:{inputs:MarketInputs,setInputs:(x:MarketInputs)=>void,run:()=>void}){const set=(k:keyof MarketInputs,v:any)=>setInputs({...inputs,[k]:v});return <div className="controls">{([['xauusd','XAUUSD'],['dxy','DXY'],['us10y','US 10Y %'],['realYield','Real Yield %']] as const).map(([k,l])=><label key={k}>{l}<input type="number" step=".01" value={inputs[k] as number} onChange={e=>set(k,+e.target.value)}/></label>)}<Select label="Fed Stance" value={inputs.fedStance} options={['VERY_HAWKISH','HAWKISH','NEUTRAL','DOVISH','VERY_DOVISH']} onChange={v=>set('fedStance',v)}/><Select label="Economic Data" value={inputs.economicData} options={['HOT','INLINE','COOL']} onChange={v=>set('economicData',v)}/><Select label="Technical" value={inputs.technicalStructure} options={['BULLISH','BEARISH','NEUTRAL']} onChange={v=>set('technicalStructure',v)}/><Select label="Liquidity" value={inputs.liquidity} options={['BUY_SIDE_NEARBY','SELL_SIDE_NEARBY','BALANCED']} onChange={v=>set('liquidity',v)}/><label className="check">Catalyst blocker<input type="checkbox" checked={inputs.eventRisk} onChange={e=>set('eventRisk',e.target.checked)}/></label><button className="primary" onClick={run}>RECALCULATE</button></div>}
function Select({label,value,options,onChange}:{label:string,value:string,options:string[],onChange:(x:string)=>void}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
