import { useCallback, useEffect, useState } from 'react';
import type { MarketTimeframe, NormalizedCandle } from '../../shared/types';
import { fetchDxyCandles } from '../api';
import { useCentralData } from '../data';
import { MarketChartCanvas, type ChartMode } from './XauUsdChart';

const duration:Record<MarketTimeframe,number>={'5M':300000,'15M':900000,'1H':3600000,'4H':14400000,'1D':86400000};
const clean=(candles:NormalizedCandle[])=>{const unique=new Map<number,NormalizedCandle>();for(const candle of candles){const stamp=Date.parse(candle.time);if(Number.isFinite(stamp)&&[candle.open,candle.high,candle.low,candle.close].every(Number.isFinite))unique.set(stamp,candle)}return [...unique.entries()].sort(([a],[b])=>a-b).map(([,bar])=>bar)};

export function DxyChart(){
  const {data}=useCentralData();const dxy=data?.dxy;const [timeframe,setTimeframe]=useState<MarketTimeframe>('1H');const [mode,setMode]=useState<ChartMode>('CANDLES');const [candles,setCandles]=useState<NormalizedCandle[]>([]);const [hovered,setHovered]=useState<NormalizedCandle|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  useEffect(()=>{let active=true;setLoading(true);setError('');fetchDxyCandles(timeframe,500).then(bars=>{if(active)setCandles(clean(bars))}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'DXY chart history unavailable')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[timeframe]);
  useEffect(()=>{if(!dxy?.value||!dxy.providerTimestamp)return;const tick=Date.parse(dxy.providerTimestamp);if(!Number.isFinite(tick))return;const start=Math.floor(tick/duration[timeframe])*duration[timeframe];const time=new Date(start).toISOString();setCandles(current=>{const next=[...current];const index=next.findIndex(c=>Date.parse(c.time)===start);if(index>=0){const candle=next[index];if(candle.close===dxy.value)return current;next[index]={...candle,high:Math.max(candle.high,dxy.value!),low:Math.min(candle.low,dxy.value!),close:dxy.value!,complete:false}}else next.push({time,open:dxy.value!,high:dxy.value!,low:dxy.value!,close:dxy.value!,volume:0,complete:false});return clean(next)})},[dxy?.value,dxy?.providerTimestamp,timeframe]);
  const loadOlder=useCallback(async()=>{const first=candles[0];if(!first)return;const older=await fetchDxyCandles(timeframe,500,first.time);setCandles(current=>clean([...older,...current]))},[candles,timeframe]);
  const shown=hovered??candles.at(-1)??null;const status=dxy?.status??'LOADING';
  return <div className="xau-chart dxy-chart"><div className="trading-chart-head"><div><h2>DXY · {timeframe}</h2><span className={`feed-state ${status.toLowerCase()}`}>*** · DEMO</span>{shown&&<span className="ohlc">O {shown.open.toFixed(3)} H {shown.high.toFixed(3)} L {shown.low.toFixed(3)} C {shown.close.toFixed(3)}</span>}</div><div className="chart-switches"><div>{(['5M','15M','1H','4H','1D'] as MarketTimeframe[]).map(value=><button key={value} className={timeframe===value?'active':''} onClick={()=>setTimeframe(value)}>{value}</button>)}</div><div>{(['LINE','CANDLES'] as ChartMode[]).map(value=><button key={value} className={mode===value?'active':''} onClick={()=>setMode(value)}>{value}</button>)}</div></div></div><div className="chart live-chart dxy-chart-area">{loading&&candles.length===0?<div className="chart-unavailable loading"><b>LOADING DEMO HISTORY...</b></div>:candles.length?<MarketChartCanvas candles={candles} mode={mode} timeframe={timeframe} defaultVisibleDays={5} onHover={setHovered} onLoadOlder={loadOlder}/>:<div className="chart-unavailable"><b>DEMO CHART UNAVAILABLE</b></div>}</div><div className="dxy-chart-footer"><span>{dxy?.value?.toFixed(3)??'—'} {dxy?.changePercent!=null?`· ${dxy.changePercent>=0?'+':''}${dxy.changePercent.toFixed(2)}%`:''}</span><span>*** · DEMO · Updated {dxy?.receivedAt?new Date(dxy.receivedAt).toLocaleTimeString():'—'}</span></div></div>
}
