import { useCallback, useEffect, useRef, useState } from 'react';
import { CandlestickSeries, ColorType, createChart, LineSeries, type IChartApi, type ISeriesApi, type LogicalRange, type UTCTimestamp } from 'lightweight-charts';
import { fetchMarketCandles, fetchMarketLevels } from '../api';
import { useMarket } from '../market';
import type { MarketLevels, MarketTimeframe, NormalizedCandle } from '../../shared/types';

export type ChartMode='LINE'|'CANDLES';
type Props={defaultTimeframe?:MarketTimeframe;defaultVisibleDays?:number;compact?:boolean;showDebug?:boolean;onLevelsChange?:(levels:MarketLevels|null)=>void};

const cleanCandles=(candles:NormalizedCandle[])=>{const unique=new Map<number,NormalizedCandle>();for(const candle of candles){const time=Math.floor(Date.parse(candle.time)/1000);if(Number.isFinite(time)&&[candle.open,candle.high,candle.low,candle.close].every(Number.isFinite))unique.set(time,candle)}return [...unique.entries()].sort(([a],[b])=>a-b)};
const timeframeMs:Record<MarketTimeframe,number>={'5M':300000,'15M':900000,'1H':3600000,'4H':14400000,'1D':86400000};

export function XauUsdChart({defaultTimeframe='1H',defaultVisibleDays,compact=false,showDebug=false,onLevelsChange}:Props){
  const [timeframe,setTimeframe]=useState<MarketTimeframe>(defaultTimeframe);const [mode,setMode]=useState<ChartMode>('CANDLES');const [candles,setCandles]=useState<NormalizedCandle[]>([]);const [levels,setLevels]=useState<MarketLevels|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [hovered,setHovered]=useState<NormalizedCandle|null>(null);const {price,snapshot,latestCandle}=useMarket();
  useEffect(()=>{let active=true;setLoading(true);setError('');setCandles([]);if(import.meta.env.DEV)console.debug(`[MARKET] requesting candles ${timeframe}`);Promise.all([fetchMarketCandles(timeframe,500),fetchMarketLevels(timeframe)]).then(([bars,nextLevels])=>{if(!active)return;if(import.meta.env.DEV)console.debug(`[MARKET] received candles: ${bars.length}`);setCandles(bars);setLevels(nextLevels);onLevelsChange?.(nextLevels)}).catch(e=>{if(!active)return;setError(e instanceof Error?e.message:'Candle data unavailable');setCandles([]);setLevels(null);onLevelsChange?.(null)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[timeframe,snapshot?.mode,onLevelsChange]);
  useEffect(()=>{if(!latestCandle||latestCandle.timeframe!==timeframe)return;setCandles(current=>{const next=[...current];const index=next.findIndex(c=>c.time===latestCandle.candle.time);if(index>=0)next[index]=latestCandle.candle;else next.push(latestCandle.candle);return cleanCandles(next).map(([,c])=>c)})},[latestCandle,timeframe]);
  useEffect(()=>{if(!price||!['LIVE','CURRENT','API'].includes(price.status))return;const tick=Date.parse(price.providerTimestamp??price.timestamp);if(!Number.isFinite(tick))return;const start=Math.floor(tick/timeframeMs[timeframe])*timeframeMs[timeframe];const time=new Date(start).toISOString();setCandles(current=>{const next=current.filter(c=>Date.parse(c.time)<=start);const index=next.findIndex(c=>Date.parse(c.time)===start);if(index>=0){const candle=next[index];next[index]={...candle,high:Math.max(candle.high,price.mid),low:Math.min(candle.low,price.mid),close:price.mid,complete:false}}else next.push({time,open:price.mid,high:price.mid,low:price.mid,close:price.mid,volume:1,complete:false});return cleanCandles(next).map(([,c])=>c)})},[price?.mid,price?.providerTimestamp,price?.receivedAt,timeframe]);
  const loadOlder=useCallback(async()=>{const first=candles[0];if(!first)return;const older=await fetchMarketCandles(timeframe,500,first.time);setCandles(current=>cleanCandles([...older,...current]).map(([,c])=>c))},[candles,timeframe]);
  const shown=hovered??candles.at(-1)??null;const status=price?.status??snapshot?.status??'DISCONNECTED';const errorLabel='DEMO MARKET DATA UNAVAILABLE';
  return <div className={`xau-chart ${compact?'compact':''}`}><div className="trading-chart-head"><div><h2>XAUUSD · {timeframe}</h2><span className={`feed-state ${status.toLowerCase()}`}>*** · DEMO</span>{shown&&<span className="ohlc">O {shown.open.toFixed(3)} H {shown.high.toFixed(3)} L {shown.low.toFixed(3)} C {shown.close.toFixed(3)}</span>}</div><div className="chart-switches"><div>{(['5M','15M','1H','4H','1D'] as MarketTimeframe[]).map(value=><button key={value} className={timeframe===value?'active':''} onClick={()=>setTimeframe(value)}>{value}</button>)}</div><div>{(['LINE','CANDLES'] as ChartMode[]).map(value=><button key={value} className={mode===value?'active':''} onClick={()=>setMode(value)}>{value}</button>)}</div></div></div><div className={`chart ${compact?'dashboard-chart':'large'} live-chart`}>{loading?<div className="chart-unavailable loading"><b>LOADING DEMO DATA...</b></div>:error?<div className="chart-unavailable"><b>{errorLabel}</b></div>:<MarketChartCanvas candles={candles} mode={mode} timeframe={timeframe} defaultVisibleDays={defaultVisibleDays} onHover={setHovered} onLoadOlder={loadOlder}/>}</div>{compact&&<div className="levels"><span>PDH <b>{levels?.previousDayHigh.toFixed(2)??'—'}</b></span><span>PDL <b>{levels?.previousDayLow.toFixed(2)??'—'}</b></span><span>DAY HIGH <b>{levels?.dayHigh.toFixed(2)??'—'}</b></span><span>ATR(14) <b>{levels?.atr14.toFixed(2)??'—'}</b></span></div>}</div>
}

export function MarketChartCanvas({candles,mode,timeframe,defaultVisibleDays,onHover,onLoadOlder}:{candles:NormalizedCandle[];mode:ChartMode;timeframe:MarketTimeframe;defaultVisibleDays?:number;onHover:(c:NormalizedCandle|null)=>void;onLoadOlder:()=>Promise<void>}){
  const host=useRef<HTMLDivElement>(null);const chartRef=useRef<IChartApi|null>(null);const seriesRef=useRef<ISeriesApi<any>|null>(null);const candlesRef=useRef(candles);const hoverRef=useRef(onHover);const olderRef=useRef(onLoadOlder);const loadingOlder=useRef(false);const initialRangeFor=useRef('');const preservedRange=useRef<LogicalRange|null>(null);const [away,setAway]=useState(false);const [light,setLight]=useState(()=>document.documentElement.dataset.theme==='light');candlesRef.current=candles;hoverRef.current=onHover;olderRef.current=onLoadOlder;
  useEffect(()=>{const observer=new MutationObserver(()=>setLight(document.documentElement.dataset.theme==='light'));observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});return()=>observer.disconnect()},[]);
  useEffect(()=>{if(!host.current)return;const background=light?'#ffffff':'#101318';const text=light?'#65707c':'#77808d';const grid=light?'#e2e5e9':'#222831';const border=light?'#cfd4da':'#2b3139';const chart=createChart(host.current,{width:host.current.clientWidth,height:host.current.clientHeight,layout:{background:{type:ColorType.Solid,color:background},textColor:text,fontFamily:'DM Mono'},grid:{vertLines:{color:grid},horzLines:{color:grid}},crosshair:{vertLine:{color:'#78818d88'},horzLine:{color:'#78818d88'}},rightPriceScale:{borderColor:border},timeScale:{borderColor:border,timeVisible:true,secondsVisible:false,rightOffset:5},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true},handleScale:{mouseWheel:true,pinch:true,axisPressedMouseMove:true}});chartRef.current=chart;const resize=new ResizeObserver(entries=>{const box=entries[0]?.contentRect;if(box?.width&&box.height)chart.resize(box.width,box.height)});resize.observe(host.current);chart.subscribeCrosshairMove(param=>{const series=seriesRef.current;if(!series)return;const point=param.seriesData.get(series) as any;if(!point){hoverRef.current(null);return}hoverRef.current(candlesRef.current.find(c=>Math.floor(Date.parse(c.time)/1000)===Number(point.time))??null)});chart.timeScale().subscribeVisibleLogicalRangeChange(range=>{if(!range)return;setAway(range.to<candlesRef.current.length-3);if(range.from<10&&!loadingOlder.current){loadingOlder.current=true;void olderRef.current().finally(()=>loadingOlder.current=false)}});return()=>{resize.disconnect();chart.remove();chartRef.current=null;seriesRef.current=null}},[light]);
  useEffect(()=>{const chart=chartRef.current;if(!chart)return;preservedRange.current=chart.timeScale().getVisibleLogicalRange();if(seriesRef.current)chart.removeSeries(seriesRef.current);seriesRef.current=mode==='CANDLES'?chart.addSeries(CandlestickSeries,{upColor:'#4fae7d',downColor:'#d66f6a',wickUpColor:'#4fae7d',wickDownColor:'#d66f6a',borderVisible:false,priceLineVisible:true,lastValueVisible:true}):chart.addSeries(LineSeries,{color:'#d6ad57',lineWidth:2,priceLineVisible:true,lastValueVisible:true})},[mode,light]);
  useEffect(()=>{const chart=chartRef.current,series=seriesRef.current;if(!chart||!series||!candles.length)return;const valid=cleanCandles(candles);if(import.meta.env.DEV){console.debug(`[CHART] valid candles: ${valid.length}`);console.debug('[CHART] first time:',valid[0]?.[0]);console.debug('[CHART] last time:',valid.at(-1)?.[0])}series.setData((mode==='CANDLES'?valid.map(([time,c])=>({time:time as UTCTimestamp,open:c.open,high:c.high,low:c.low,close:c.close})):valid.map(([time,c])=>({time:time as UTCTimestamp,value:c.close}))) as any);if(initialRangeFor.current!==timeframe){const last=valid.at(-1)?.[0];if(defaultVisibleDays&&timeframe==='1H'&&last){chart.timeScale().setVisibleRange({from:(last-defaultVisibleDays*86400) as UTCTimestamp,to:last as UTCTimestamp})}else chart.timeScale().setVisibleLogicalRange({from:Math.max(0,valid.length-100),to:valid.length-1});initialRangeFor.current=timeframe;preservedRange.current=null}else if(preservedRange.current){chart.timeScale().setVisibleLogicalRange(preservedRange.current);preservedRange.current=null}},[candles,mode,timeframe,defaultVisibleDays,light]);
  return <><div ref={host} className="chart-canvas"/>{away&&<button className="go-live" onClick={()=>chartRef.current?.timeScale().scrollToRealTime()}>GO TO LIVE</button>}</>
}
