import * as signalR from '@microsoft/signalr';
import type { DataStatus, DxySnapshot, MarketTimeframe, NormalizedCandle } from '../../shared/types.js';

type Tick={symbol?:string;description?:string;bid?:number;ask?:number;mid?:number;high?:number;low?:number;dayDiffPercent?:number;timestamp?:string;marketState?:string;stale?:boolean;quoteAgeSeconds?:number};

export class BiQuoteDxyProvider {
  readonly refreshInterval=Math.max(60000,Number(process.env.BIQUOTE_DXY_REST_INTERVAL_MS)||300000);
  private readonly restUrl='https://biquote.io/api/DXY';private readonly hubUrl='https://biquote.io/hubs/tick';private readonly staleAfterMs=Math.max(120000,Number(process.env.BIQUOTE_DXY_STALE_AFTER_MS)||300000);
  private cache:DxySnapshot|null=null;private inflight?:Promise<DxySnapshot>;private connection?:signalR.HubConnection;private listeners=new Set<(snapshot:DxySnapshot)=>void>();private reconnecting=false;private started=false;private candleCache=new Map<string,{expires:number;value:NormalizedCandle[];inflight?:Promise<NormalizedCandle[]>}>();
  constructor(){console.info('[BIQUOTE] DXY provider initialized')}
  subscribe(listener:(snapshot:DxySnapshot)=>void){this.listeners.add(listener);if(this.cache)listener(this.view());return()=>this.listeners.delete(listener)}
  start(){if(this.started)return;this.started=true;void this.refresh().catch(()=>{});void this.connectStream()}
  stop(){this.started=false;void this.connection?.stop();this.connection=undefined}
  async getSnapshot(force=false){if(force)return this.refresh();if(!this.cache)return this.refresh();if(Date.now()-Date.parse(this.cache.receivedAt??this.cache.timestamp??'')>this.refreshInterval)void this.refresh().catch(()=>{});return this.view()}
  refresh(){if(this.inflight)return this.inflight;this.inflight=this.loadRest().finally(()=>{this.inflight=undefined});return this.inflight}
  async getCandles(timeframe:MarketTimeframe,count=500,before?:string){const intervals:Record<MarketTimeframe,string>={'5M':'5m','15M':'15m','1H':'1h','4H':'4h','1D':'1d'};const safe=Math.min(1000,Math.max(15,Math.floor(count)));const params=new URLSearchParams({interval:intervals[timeframe],limit:String(safe)});if(before)params.set('to',before);const key=`${timeframe}:${safe}:${before??'latest'}`;const cached=this.candleCache.get(key);if(cached?.value.length&&cached.expires>Date.now())return cached.value;if(cached?.inflight)return cached.inflight;const load=(async()=>{const response=await fetch(`https://biquote.io/api/DXY/ohlc?${params}`,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error(`BIQUOTE DXY OHLC HTTP ${response.status}`);const json=await response.json() as {symbol?:string;bars?:Array<{openTime?:string;open?:number;high?:number;low?:number;close?:number;volume?:number;isOpen?:boolean}>};if(String(json.symbol).toUpperCase()!=='DXY'||!Array.isArray(json.bars))throw new Error('Invalid BiQuote DXY OHLC response');const unique=new Map<number,NormalizedCandle>();for(const bar of json.bars){const stamp=Date.parse(bar.openTime??'');const open=Number(bar.open),high=Number(bar.high),low=Number(bar.low),close=Number(bar.close);if(!Number.isFinite(stamp)||![open,high,low,close].every(Number.isFinite))continue;unique.set(stamp,{time:new Date(stamp).toISOString(),open,high,low,close,volume:Number.isFinite(Number(bar.volume))?Number(bar.volume):0,complete:bar.isOpen!==true})}const bars=[...unique.entries()].sort(([a],[b])=>a-b).map(([,bar])=>bar);if(!bars.length)throw new Error('BiQuote returned no valid DXY candles');this.candleCache.set(key,{expires:Date.now()+(before?3600000:60000),value:bars});return bars})();this.candleCache.set(key,{expires:cached?.expires??0,value:cached?.value??[],inflight:load});try{return await load}catch(error){if(cached?.value.length)return cached.value;this.candleCache.delete(key);throw error}}
  private async loadRest(){console.info('[BIQUOTE] Requesting DXY snapshot');try{const response=await fetch(this.restUrl,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(12000)});console.info(`[BIQUOTE] REST status: ${response.status}`);const raw=await response.json() as Tick;if(!response.ok)throw new Error(`BIQUOTE HTTP ${response.status}`);const snapshot=this.normalize(raw,'API');this.cache=snapshot;console.info(`[BIQUOTE] DXY snapshot: ${snapshot.value}`);console.info('[BIQUOTE] DXY cache updated');this.emit();return this.view()}catch(error){const message=error instanceof Error?error.message:'BiQuote DXY unavailable';if(this.cache){this.cache={...this.cache,status:this.isStale()?'STALE':'CACHED',message};return this.view()}return this.empty('UNAVAILABLE',message)}}
  private async connectStream(){if(!this.started||this.connection)return;console.info('[BIQUOTE] Connecting DXY stream');const connection=new signalR.HubConnectionBuilder().withUrl(this.hubUrl).withAutomaticReconnect([0,1000,2000,5000,10000,30000]).configureLogging(signalR.LogLevel.Warning).build();this.connection=connection;connection.on('ReceiveSubscriptionState',()=>{});connection.on('ReceiveTick',(raw:Tick)=>{if(String(raw.symbol).toUpperCase()!=='DXY')return;try{const next=this.normalize(raw,'LIVE STREAM');const prior=Date.parse(this.cache?.providerTimestamp??'');if(Number.isFinite(prior)&&Date.parse(next.providerTimestamp??'')<prior)return;if(this.cache?.value===next.value&&this.cache.providerTimestamp===next.providerTimestamp)return;this.cache=next;if(process.env.NODE_ENV!=='production'){console.debug(`[BIQUOTE] DXY tick: ${next.value}`);console.debug('[BIQUOTE] DXY cache updated')}this.emit()}catch(error){console.warn('[BIQUOTE] malformed DXY tick ignored:',error instanceof Error?error.message:error)}});connection.onreconnecting(()=>{this.reconnecting=true;if(this.cache)this.cache={...this.cache,status:'RECONNECTING'};console.warn('[BIQUOTE] DXY stream disconnected');console.info('[BIQUOTE] DXY reconnecting');this.emit()});connection.onreconnected(async()=>{this.reconnecting=false;console.info('[BIQUOTE] DXY stream connected');await connection.invoke('Subscribe',['DXY']);void this.refresh().catch(()=>{})});connection.onclose(()=>{console.warn('[BIQUOTE] DXY stream disconnected');this.connection=undefined;if(this.started)setTimeout(()=>void this.connectStream(),30000)});try{await connection.start();await connection.invoke('Subscribe',['DXY']);this.reconnecting=false;console.info('[BIQUOTE] DXY stream connected')}catch(error){console.warn('[BIQUOTE] DXY stream failed:',error instanceof Error?error.message:error);this.connection=undefined;if(this.started)setTimeout(()=>void this.connectStream(),30000)}}
  private normalize(raw:Tick,transport:'LIVE STREAM'|'API'):DxySnapshot{if(String(raw.symbol).toUpperCase()!=='DXY')throw new Error('BiQuote response is not DXY');const value=Number(raw.mid);const providerTimestamp=raw.timestamp?new Date(raw.timestamp).toISOString():null;if(!Number.isFinite(value)||!providerTimestamp||!Number.isFinite(Date.parse(providerTimestamp)))throw new Error('BiQuote DXY response has no valid price or timestamp');const receivedAt=new Date().toISOString();const percent=Number(raw.dayDiffPercent);const changePercent=Number.isFinite(percent)?percent:null;const open=changePercent!=null?value/(1+changePercent/100):null;const change=open!=null?value-open:null;const providerStale=raw.stale===true||raw.marketState==='closed';return {symbol:'DXY',value,previousClose:null,change:Number.isFinite(change)?change:null,changePercent,dayHigh:Number.isFinite(Number(raw.high))?Number(raw.high):null,dayLow:Number.isFinite(Number(raw.low))?Number(raw.low):null,timestamp:providerTimestamp,providerTimestamp,receivedAt,lastSuccessfulUpdate:receivedAt,source:'BIQUOTE',transport,lastUpdated:receivedAt,status:transport==='LIVE STREAM'&&!providerStale?'LIVE':providerStale?'CACHED':'API',message:raw.marketState==='closed'?'Market closed · last known price':undefined}}
  private view(){if(!this.cache)return this.empty('UNAVAILABLE','DXY data unavailable');if(this.reconnecting)return {...this.cache,status:'RECONNECTING' as const};if(this.isStale()&&this.cache.status==='LIVE')return {...this.cache,status:'STALE' as const,message:'BiQuote DXY stream has stopped updating'};return {...this.cache}}
  private isStale(){return Boolean(this.cache?.receivedAt&&Date.now()-Date.parse(this.cache.receivedAt)>this.staleAfterMs)}
  private emit(){const snapshot=this.view();this.listeners.forEach(listener=>listener(snapshot))}
  private empty(status:DataStatus,message:string):DxySnapshot{return {symbol:'DXY',value:null,previousClose:null,change:null,changePercent:null,dayHigh:null,dayLow:null,timestamp:null,providerTimestamp:null,receivedAt:null,lastSuccessfulUpdate:null,source:'BIQUOTE',transport:null,lastUpdated:null,status,message}}
}
