import type { FedWatchMeeting, FedWatchSnapshot } from '../../shared/types.js';

export class CmeFedWatchProvider {
  private key=process.env.CME_FEDWATCH_API_KEY?.trim()||'';private url=process.env.CME_FEDWATCH_API_URL?.trim()||'';private cache?:FedWatchSnapshot;private expires=0;private inflight?:Promise<FedWatchSnapshot>;
  constructor(){console.info('[CME FEDWATCH] Provider selected');console.info(`[CME FEDWATCH] API configured: ${this.key&&this.url?'yes':'no'}`)}
  async getSnapshot(){if(!this.key||!this.url)return this.empty('NOT_CONFIGURED','CME API NOT CONFIGURED');if(this.cache&&Date.now()<this.expires)return this.cache;if(this.inflight)return this.inflight;this.inflight=this.load().finally(()=>this.inflight=undefined);return this.inflight}
  private async load():Promise<FedWatchSnapshot>{try{const response=await fetch(this.url,{headers:{Authorization:`Bearer ${this.key}`,Accept:'application/json'},signal:AbortSignal.timeout(15000)});if(response.status===429)return this.empty('RATE_LIMITED','CME API rate limited');if(response.status===401||response.status===403)return this.empty('UNAVAILABLE','CME authentication failed');if(!response.ok)throw new Error(`CME API HTTP ${response.status}`);const raw=await response.json() as any;const currentTargetRange=String(raw.currentTargetRange??raw.current_target_range??'');const meetings:FedWatchMeeting[]=(raw.meetings??[]).map((m:any)=>({date:new Date(m.date).toISOString(),probabilities:(m.probabilities??[]).map((p:any)=>({targetRange:String(p.targetRange??p.target_range),probability:Number(p.probability)})).filter((p:any)=>Number.isFinite(p.probability))})).filter((m:FedWatchMeeting)=>m.probabilities.length).sort((a:FedWatchMeeting,b:FedWatchMeeting)=>Date.parse(a.date)-Date.parse(b.date));const nextMeeting=meetings.find(m=>Date.parse(m.date)>=Date.now())??meetings[0]??null;const summary=nextMeeting?this.aggregate(currentTargetRange,nextMeeting):null;const snapshot:FedWatchSnapshot={currentTargetRange:currentTargetRange||null,nextMeeting,meetings,summary,timestamp:new Date(raw.timestamp??Date.now()).toISOString(),source:'CME FedWatch',lastUpdated:new Date().toISOString(),status:raw.frequency==='EOD'?'EOD':'LIVE'};this.cache=snapshot;this.expires=Date.now()+Math.max(300000,Number(process.env.CME_FEDWATCH_REFRESH_MS)||900000);console.info(`[CME FEDWATCH] Meetings loaded: ${meetings.length}`);console.info(`[CME FEDWATCH] Next meeting: ${nextMeeting?.date??'none'}`);console.info(`[CME FEDWATCH] Data timestamp: ${snapshot.timestamp}`);return snapshot}catch(error){return this.empty('UNAVAILABLE',error instanceof Error?error.message:'CME FedWatch unavailable')}}
  private aggregate(current:string,meeting:FedWatchMeeting){const midpoint=(range:string)=>{const numbers=range.match(/\d+(?:\.\d+)?/g)?.map(Number)??[];return numbers.length>=2?(numbers[0]+numbers[1])/2:NaN};const currentMid=midpoint(current);return meeting.probabilities.reduce((sum,p)=>{const value=midpoint(p.targetRange);if(value<currentMid)sum.easing+=p.probability;else if(value>currentMid)sum.hike+=p.probability;else sum.unchanged+=p.probability;return sum},{easing:0,unchanged:0,hike:0})}
  private empty(status:FedWatchSnapshot['status'],message:string):FedWatchSnapshot{return {currentTargetRange:null,nextMeeting:null,meetings:[],summary:null,timestamp:null,source:'CME FedWatch',lastUpdated:new Date().toISOString(),status,message}}
}
