import type { DxySnapshot } from '../../shared/types.js';

export class TwelveDataDxyProvider {
  private readonly key=process.env.TWELVE_DATA_API_KEY?.trim()||'';private readonly ttl=Math.max(60000,Number(process.env.DXY_POLL_INTERVAL_MS)||60000);private cache:DxySnapshot|null=null;private expires=0;private inflight?:Promise<DxySnapshot>;private symbol:string|null|undefined;
  async getSnapshot(){if(this.cache&&Date.now()<this.expires)return this.cache;if(this.inflight)return this.inflight;this.inflight=this.load().finally(()=>this.inflight=undefined);return this.inflight}
  private async load():Promise<DxySnapshot>{if(!this.key)return this.result('NOT_CONFIGURED','Twelve Data API key not configured');try{const symbol=await this.resolve();if(!symbol)return this.result('UNAVAILABLE','Actual U.S. Dollar Index is not available on this Twelve Data account; no proxy was substituted');const response=await this.request(`/quote?symbol=${encodeURIComponent(symbol)}`);const value=Number(response.close??response.price),previousClose=Number(response.previous_close),dayHigh=Number(response.high),dayLow=Number(response.low);if(!Number.isFinite(value)||!Number.isFinite(previousClose))throw new Error('DXY quote unavailable');const change=value-previousClose,changePercent=previousClose?change/previousClose*100:0;const snapshot:DxySnapshot={symbol,value,previousClose,change,changePercent,dayHigh:Number.isFinite(dayHigh)?dayHigh:null,dayLow:Number.isFinite(dayLow)?dayLow:null,timestamp:response.datetime?new Date(response.datetime).toISOString():new Date().toISOString(),source:'TWELVE DATA',lastUpdated:new Date().toISOString(),status:'API'};this.cache=snapshot;this.expires=Date.now()+this.ttl;console.info(`[TWELVE DATA] DXY price: ${value}`);return snapshot}catch(error){const message=error instanceof Error?error.message:'DXY unavailable';return this.result(/rate/i.test(message)?'RATE_LIMITED':'UNAVAILABLE',message)}}
  private async resolve(){if(this.symbol!==undefined)return this.symbol;console.info('[TWELVE DATA] Resolving DXY symbol');const catalog=await this.request('/indices?symbol=DXY&show_plan=true');const match=(catalog.data??[]).find((x:any)=>x.symbol==='DXY'&&/dollar index/i.test(x.name??x.instrument_name??''));this.symbol=match?.symbol??null;console.info(`[TWELVE DATA] DXY symbol resolved: ${this.symbol??'UNAVAILABLE'}`);return this.symbol}
  private async request(path:string){const response=await fetch(`https://api.twelvedata.com${path}`,{headers:{Authorization:`apikey ${this.key}`},signal:AbortSignal.timeout(12000)});const json=await response.json() as any;if(response.status===429||json.code===429)throw new Error('Twelve Data rate limited');if(!response.ok||json.status==='error')throw new Error(String(json.message??`HTTP ${response.status}`));return json}
  private result(status:DxySnapshot['status'],message:string):DxySnapshot{const snapshot:DxySnapshot={symbol:null,value:null,previousClose:null,change:null,changePercent:null,dayHigh:null,dayLow:null,timestamp:null,source:'TWELVE DATA',lastUpdated:new Date().toISOString(),status,message};this.cache=snapshot;this.expires=Date.now()+this.ttl;return snapshot}
}
