import type { DataStatus, FedRateExpectationsSnapshot, RefreshMetadata } from '../../shared/types.js';

export interface FedRateExpectationsProvider {getSnapshot(force?:boolean):Promise<FedRateExpectationsSnapshot>;refresh():Promise<FedRateExpectationsSnapshot>}
type Instrument={symbol:string;name:string;exchange:string;type:string};

export class TwelveDataFedRateExpectationsProvider implements FedRateExpectationsProvider {
  readonly refreshInterval=Math.max(900000,Number(process.env.FED_EXPECTATIONS_REFRESH_MS)||21600000);
  private readonly key=process.env.TWELVE_DATA_API_KEY?.trim()||'';private cache:FedRateExpectationsSnapshot|null=null;private inflight?:Promise<FedRateExpectationsSnapshot>;private lastAttempt:string|null=null;private lastSuccessfulFetch:string|null=null;private lastError:string|null=null;private consecutiveFailures=0;
  async getSnapshot(force=false){if(force)return this.refresh();if(this.cache&&this.lastAttempt&&Date.now()-Date.parse(this.lastAttempt)<this.refreshInterval)return this.view();return this.refresh()}
  refresh(){if(this.inflight)return this.inflight;this.inflight=this.load().finally(()=>{this.inflight=undefined});return this.inflight}
  private async load():Promise<FedRateExpectationsSnapshot>{this.lastAttempt=new Date().toISOString();console.info('[FED EXPECTATIONS] discovery refresh started');try{const nextMeetingDate=await this.nextFomcMeeting();if(!this.key){this.lastError='TWELVE DATA NOT CONFIGURED';return this.saveUnavailable('NOT_CONFIGURED',nextMeetingDate,[])}const instruments=await this.discover();if(!instruments.length){this.lastError='Twelve Data returned no 30-Day Federal Funds futures instruments';return this.saveUnavailable('UNAVAILABLE',nextMeetingDate,[])}this.lastError='Fed Funds instruments found, but contract-price integration is not supported';return this.saveUnavailable('UNAVAILABLE',nextMeetingDate,instruments)}catch(error){this.consecutiveFailures++;this.lastError=error instanceof Error?error.message:'Fed expectations unavailable';console.error(`[FED EXPECTATIONS] refresh failed: ${this.lastError}`);return this.saveUnavailable('UNAVAILABLE',this.cache?.nextMeetingDate??null,this.cache?.instruments??[])}}
  private async discover():Promise<Instrument[]>{const found=new Map<string,Instrument>();for(const term of ['30-Day Federal Funds Futures','Federal Funds Futures','Fed Funds Futures','ZQ']){const url=new URL('https://api.twelvedata.com/symbol_search');url.searchParams.set('symbol',term);url.searchParams.set('outputsize','120');const response=await fetch(url,{headers:{Authorization:`apikey ${this.key}`},signal:AbortSignal.timeout(15000)});console.info(`[FED EXPECTATIONS] Twelve Data search "${term}" HTTP ${response.status}`);const json=await response.json() as any;if(!response.ok)throw new Error(`Twelve Data discovery HTTP ${response.status}`);for(const item of json.data??[]){const text=[item.symbol,item.instrument_name,item.name,item.exchange].join(' ');if(!/fed(eral)? funds|30.day/i.test(text))continue;const instrument={symbol:String(item.symbol),name:String(item.instrument_name??item.name??''),exchange:String(item.exchange??''),type:String(item.instrument_type??item.type??'')};found.set(`${instrument.symbol}:${instrument.exchange}`,instrument)}}console.info(`[FED EXPECTATIONS] Fed Funds instruments found: ${found.size}`);return [...found.values()]}
  private async nextFomcMeeting():Promise<string|null>{const response=await fetch('https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',{headers:{'User-Agent':'GOLD-INTEL/1.0'},signal:AbortSignal.timeout(15000)});console.info(`[FED EXPECTATIONS] Federal Reserve calendar HTTP ${response.status}`);if(!response.ok)throw new Error(`Federal Reserve calendar HTTP ${response.status}`);const html=await response.text();const meetings:Array<{date:string,time:number}>=[];for(const yearMatch of html.matchAll(/<a id="[^"]+">(20\d{2}) FOMC Meetings<\/a>([\s\S]*?)(?=<a id="[^"]+">20\d{2} FOMC Meetings|$)/g)){const year=Number(yearMatch[1]);for(const meeting of yearMatch[2].matchAll(/fomc-meeting__month[^>]*><strong>([A-Za-z]+)<\/strong>[\s\S]*?fomc-meeting__date[^>]*>([^<]+)/g)){const month=new Date(`${meeting[1]} 1, ${year}`).getMonth();const days=meeting[2].match(/\d+/g)?.map(Number)??[];const day=days.at(-1);if(day==null||month<0)continue;const time=Date.UTC(year,month,day,23,59,59);meetings.push({date:new Date(Date.UTC(year,month,day)).toISOString().slice(0,10),time})}}const next=meetings.sort((a,b)=>a.time-b.time).find(item=>item.time>=Date.now())?.date??null;console.info(`[FED EXPECTATIONS] next FOMC meeting: ${next??'unavailable'}`);return next}
  private saveUnavailable(status:DataStatus,nextMeetingDate:string|null,instruments:Instrument[]){this.cache={nextMeetingDate,decreaseProbability:null,unchangedProbability:null,increaseProbability:null,source:'TWELVE DATA / FED FUNDS FUTURES',lastUpdated:null,status,message:this.lastError??undefined,instruments,...this.meta(),isRefreshing:false};return this.cache}
  private meta():RefreshMetadata{return {lastAttempt:this.lastAttempt,lastSuccessfulFetch:this.lastSuccessfulFetch,lastError:this.lastError,cacheAge:this.lastSuccessfulFetch?Date.now()-Date.parse(this.lastSuccessfulFetch):null,isRefreshing:Boolean(this.inflight),consecutiveFailures:this.consecutiveFailures}}
  private view(){return {...this.cache!,...this.meta(),isRefreshing:false}}
}
