import type { DataStatus, FredRateSnapshot, RefreshMetadata } from '../../shared/types.js';

type FredObservation={date?:string;value?:string};
const blankMeta:RefreshMetadata={lastAttempt:null,lastSuccessfulFetch:null,lastError:null,cacheAge:null,isRefreshing:false,consecutiveFailures:0};
export function normalizeEffr(observations:FredObservation[],lastUpdated=new Date().toISOString()):FredRateSnapshot{const valid=observations.filter(x=>Boolean(x.date)&&Boolean(x.value?.trim())&&x.value!=='.').map(x=>({date:x.date!,value:Number(x.value)})).filter(x=>Number.isFinite(x.value));if(valid.length<2)return {rate:null,previousRate:null,change:null,observationDate:null,source:'FRED / EFFR',lastUpdated,status:'UNAVAILABLE',message:'FRED returned fewer than two valid EFFR observations',...blankMeta};const [latest,previous]=valid;return {rate:latest.value,previousRate:previous.value,change:+(latest.value-previous.value).toFixed(4),observationDate:latest.date,source:'FRED / EFFR',lastUpdated,status:'CURRENT',...blankMeta}}

export class FredFedRateProvider {
  readonly refreshInterval=Math.max(3600000,Number(process.env.FRED_REFRESH_INTERVAL_MS)||21600000);private readonly key=process.env.FRED_API_KEY?.trim()||'';private cache:FredRateSnapshot|null=null;private lastAttempt:string|null=null;private lastSuccessfulFetch:string|null=null;private lastError:string|null=null;private lastFailureStatus:DataStatus='UNAVAILABLE';private consecutiveFailures=0;private inflight?:Promise<FredRateSnapshot>;
  constructor(){console.info('[FRED] Provider initialized');console.info(`[FRED] API key configured: ${this.key?'yes':'no'}`)}
  async getSnapshot(force=false):Promise<FredRateSnapshot>{if(!this.key)return this.empty('NOT_CONFIGURED','FRED NOT CONFIGURED');if(force)return this.refresh();if(!this.cache){if(this.lastAttempt&&Date.now()-Date.parse(this.lastAttempt)<this.refreshInterval)return this.empty(this.lastFailureStatus,this.lastError??'FRED unavailable');return this.refresh()}if(this.age()>=this.refreshInterval)void this.refresh();return this.view()}
  refresh():Promise<FredRateSnapshot>{if(this.inflight)return this.inflight;this.inflight=this.load().finally(()=>{this.inflight=undefined});return this.inflight}
  private async load():Promise<FredRateSnapshot>{this.lastAttempt=new Date().toISOString();console.info('[FRED] refresh started');console.info(`[FRED] API key configured: ${this.key?'yes':'no'}`);try{const params=new URLSearchParams({series_id:'EFFR',api_key:this.key,file_type:'json',sort_order:'desc',limit:'10'});const response=await fetch(`https://api.stlouisfed.org/fred/series/observations?${params}`,{signal:AbortSignal.timeout(15000)});console.info(`[FRED] HTTP status: ${response.status}`);const json=await response.json() as any;if(!response.ok){const error=new Error(String(json.error_message??`FRED HTTP ${response.status}`));(error as any).status=response.status;throw error}const observations=json.observations??[];console.info(`[FRED] observations received: ${Array.isArray(observations)?observations.length:0}`);const now=new Date().toISOString();const snapshot=normalizeEffr(observations,now);if(snapshot.rate==null)throw new Error(snapshot.message);this.lastSuccessfulFetch=now;this.lastError=null;this.consecutiveFailures=0;this.cache=snapshot;console.info(`[FRED] latest valid observation: ${snapshot.observationDate} (${snapshot.rate})`);console.info('[FRED] cache updated');return this.view()}catch(error){this.consecutiveFailures++;this.lastError=error instanceof Error?error.message:'FRED refresh failed';console.error(`[FRED] refresh failed: ${this.lastError}`);if(this.cache)return this.view();const code=(error as any)?.status;this.lastFailureStatus=code===429?'RATE_LIMITED':code===400&&/api key/i.test(this.lastError)?'INVALID_API_KEY':'UNAVAILABLE';return this.empty(this.lastFailureStatus,this.lastError)}}
  private age(){return this.lastSuccessfulFetch?Date.now()-Date.parse(this.lastSuccessfulFetch):Infinity}
  private meta():RefreshMetadata{return {lastAttempt:this.lastAttempt,lastSuccessfulFetch:this.lastSuccessfulFetch,lastError:this.lastError,cacheAge:Number.isFinite(this.age())?this.age():null,isRefreshing:Boolean(this.inflight),consecutiveFailures:this.consecutiveFailures}}
  private view():FredRateSnapshot{const age=this.age();const status:DataStatus=this.lastError?(age<=this.refreshInterval?'CACHED':'STALE'):'CURRENT';return {...this.cache!,status,message:this.lastError??undefined,...this.meta(),isRefreshing:false}}
  private empty(status:FredRateSnapshot['status'],message:string):FredRateSnapshot{return {rate:null,previousRate:null,change:null,observationDate:null,source:'FRED / EFFR',lastUpdated:null,status,message,...this.meta(),isRefreshing:false}}
}
