import type { MarketLevels, MarketMode, MarketSnapshot, MarketTimeframe, NormalizedCandle, NormalizedPrice } from '../../shared/types.js';
import type { MarketDataProvider } from './market.js';
import { technicalLevels } from './market.js';
import { MockMarketDataProvider } from './mockMarketDataProvider.js';
import { OandaMarketDataProvider } from './oandaMarketDataProvider.js';
import { TwelveDataMarketDataProvider } from './twelveDataMarketDataProvider.js';

export class MarketDataService {
  private mock=new MockMarketDataProvider(); private oanda=new OandaMarketDataProvider(); private twelveData=new TwelveDataMarketDataProvider(); private provider:MarketDataProvider; private listeners=new Set<(p:NormalizedPrice)=>void>(); private candleListeners=new Set<(timeframe:MarketTimeframe,candle:NormalizedCandle)=>void>(); private unsubscribe?:()=>void; private candleCache=new Map<MarketTimeframe,NormalizedCandle[]>(); private latestPrice:NormalizedPrice|null=null; private lastLog=0; private lastCandleLog=new Map<MarketTimeframe,number>();
  constructor(mode:MarketMode){this.provider=mode==='LIVE'?this.liveProvider():this.mock;this.activate()}
  get active(){return this.provider}
  setMode(mode:MarketMode){if(this.provider.mode===mode)return;this.provider.stop();this.unsubscribe?.();this.candleCache.clear();this.latestPrice=null;this.provider=mode==='LIVE'?this.liveProvider():this.mock;this.activate()}
  subscribe(listener:(p:NormalizedPrice)=>void){this.listeners.add(listener);return()=>this.listeners.delete(listener)}
  subscribeCandle(listener:(timeframe:MarketTimeframe,candle:NormalizedCandle)=>void){this.candleListeners.add(listener);return()=>this.candleListeners.delete(listener)}
  async getCurrentPrice(){return this.provider.getCurrentPrice()}
  async refreshCurrentPrice(){return this.provider.refreshCurrentPrice?this.provider.refreshCurrentPrice():this.provider.getCurrentPrice()}
  async getCandles(timeframe:MarketTimeframe,count:number,before?:string){let cached=this.candleCache.get(timeframe);if(before){const older=await this.provider.getCandles(timeframe,count,before);const merged=[...older,...(cached??[])].filter((c,i,a)=>a.findIndex(x=>x.time===c.time)===i).sort((a,b)=>Date.parse(a.time)-Date.parse(b.time));this.candleCache.set(timeframe,merged.slice(-5000));return older}if(!cached||cached.length<count){cached=await this.provider.getCandles(timeframe,Math.max(500,count));this.candleCache.set(timeframe,cached)}return cached.slice(-count)}
  async getLevels(timeframe:MarketTimeframe='1H'):Promise<MarketLevels>{const candles=await this.getCandles(timeframe,100);const daily=await this.getCandles('1D',20);return technicalLevels(candles,daily,timeframe,this.provider.source,this.provider.getStatus())}
  async getSnapshot():Promise<MarketSnapshot>{if(!this.provider.isConfigured())return this.provider.getSnapshot();const staleAfterMs=this.provider.source==='TWELVE_DATA'?(Number(process.env.TWELVE_DATA_POLL_INTERVAL_MS)||60000)*2:Number(process.env.OANDA_STALE_AFTER_MS)||15000;try{return {price:this.latestPrice??await this.getCurrentPrice(),levels:await this.getLevels(),configured:true,mode:this.provider.mode,status:this.provider.getStatus(),staleAfterMs}}catch(e){return {price:this.latestPrice,levels:null,configured:true,mode:this.provider.mode,status:this.provider.getStatus(),staleAfterMs,message:e instanceof Error?e.message:'Market data unavailable'}}}
  private activate(){this.unsubscribe=this.provider.subscribeToPrice(p=>{this.latestPrice=p;this.updateCandles(p);if(Date.now()-this.lastLog>5000){console.info(`[${p.source}] XAU_USD bid=${p.bid} ask=${p.ask} mid=${p.mid}`);this.lastLog=Date.now()}this.listeners.forEach(l=>l(p))});this.provider.start()}
  private liveProvider(){return process.env.MARKET_DATA_PROVIDER?.toLowerCase()==='oanda'?this.oanda:this.twelveData}
  private updateCandles(price:NormalizedPrice){for(const [timeframe,candles] of this.candleCache){if(!candles.length)continue;const duration:{[K in MarketTimeframe]:number}={'5M':300000,'15M':900000,'1H':3600000,'4H':14400000,'1D':86400000};let current=candles.at(-1)!;const tick=Date.parse(price.timestamp);let start=Date.parse(current.time);if(tick>=start+duration[timeframe]){start=Math.floor(tick/duration[timeframe])*duration[timeframe];current={time:new Date(start).toISOString(),open:price.mid,high:price.mid,low:price.mid,close:price.mid,volume:1,complete:false};candles.push(current);if(candles.length>5000)candles.shift()}else{current={...current,high:Math.max(current.high,price.mid),low:Math.min(current.low,price.mid),close:price.mid,volume:current.volume+1,complete:false};candles[candles.length-1]=current}if(Date.now()-(this.lastCandleLog.get(timeframe)??0)>5000){console.debug(`[CANDLE] Updating ${timeframe} ${current.time} O=${current.open} H=${current.high} L=${current.low} C=${current.close}`);this.lastCandleLog.set(timeframe,Date.now())}this.candleListeners.forEach(l=>l(timeframe,{...current}))}}
}
