import type { MarketSnapshot, MarketStatus, MarketTimeframe, NormalizedCandle, NormalizedPrice } from '../../shared/types.js';
import { technicalLevels, TIMEFRAME_GRANULARITY, type MarketDataProvider } from './market.js';

type OandaPrice={type?:string;instrument:string;time:string;bids?:{price:string}[];asks?:{price:string}[];closeoutBid?:string;closeoutAsk?:string};
export class OandaMarketDataProvider implements MarketDataProvider {
  readonly source='OANDA' as const; readonly mode='LIVE' as const;
  private token=process.env.OANDA_API_TOKEN?.trim()||''; private account=process.env.OANDA_ACCOUNT_ID?.trim()||'';
  private environment=process.env.OANDA_ENVIRONMENT==='live'?'live':'practice'; private staleAfter=Number(process.env.OANDA_STALE_AFTER_MS)||15000;
  private listeners=new Set<(p:NormalizedPrice)=>void>(); private latest:NormalizedPrice|null=null; private abort?:AbortController; private retry?:NodeJS.Timeout; private attempt=0; private connected=false;
  private get restBase(){return this.environment==='live'?'https://api-fxtrade.oanda.com':'https://api-fxpractice.oanda.com'}
  private get streamBase(){return this.environment==='live'?'https://stream-fxtrade.oanda.com':'https://stream-fxpractice.oanda.com'}
  isConfigured(){return Boolean(this.token&&this.account)}
  getStatus():MarketStatus{if(!this.isConfigured())return 'NOT_CONFIGURED';if(this.latest&&Date.now()-Date.parse(this.latest.timestamp)>this.staleAfter)return 'STALE';if(this.retry)return 'RECONNECTING';return this.connected&&this.latest?'LIVE':'DISCONNECTED'}
  async getCurrentPrice(){if(this.latest)return {...this.latest,status:this.getStatus()};const json=await this.request(`/v3/accounts/${encodeURIComponent(this.account)}/pricing?instruments=XAU_USD`);const p=this.normalize(json.prices?.[0]);this.latest=p;return p}
  async getCandles(timeframe:MarketTimeframe,count:number,before?:string):Promise<NormalizedCandle[]>{const safe=Math.min(5000,Math.max(15,Math.floor(count)));const to=before?`&to=${encodeURIComponent(before)}`:'';const json=await this.request(`/v3/instruments/XAU_USD/candles?price=M&granularity=${TIMEFRAME_GRANULARITY[timeframe]}&count=${safe}${to}`);return (json.candles||[]).map((c:any)=>({time:c.time,open:Number(c.mid.o),high:Number(c.mid.h),low:Number(c.mid.l),close:Number(c.mid.c),volume:Number(c.volume),complete:Boolean(c.complete)}))}
  async getLevels(timeframe:MarketTimeframe='1H'){return technicalLevels(await this.getCandles(timeframe,100),await this.getCandles('1D',20),timeframe,this.source,this.getStatus())}
  async getSnapshot():Promise<MarketSnapshot>{if(!this.isConfigured())return {price:null,levels:null,configured:false,mode:this.mode,status:'NOT_CONFIGURED',staleAfterMs:this.staleAfter,message:'OANDA NOT CONFIGURED'};try{return {price:await this.getCurrentPrice(),levels:await this.getLevels(),configured:true,mode:this.mode,status:this.getStatus(),staleAfterMs:this.staleAfter}}catch(e){return {price:this.latest?{...this.latest,status:this.getStatus()}:null,levels:null,configured:true,mode:this.mode,status:this.getStatus(),staleAfterMs:this.staleAfter,message:e instanceof Error?e.message:'OANDA unavailable'}}}
  subscribeToPrice(listener:(p:NormalizedPrice)=>void){this.listeners.add(listener);if(this.latest)listener({...this.latest,status:this.getStatus()});return()=>this.listeners.delete(listener)}
  start(){if(!this.isConfigured()||this.abort||this.retry)return;void this.openStream()}
  stop(){this.abort?.abort();this.abort=undefined;if(this.retry)clearTimeout(this.retry);this.retry=undefined;this.connected=false}
  private async request(path:string){if(!this.isConfigured())throw new Error('OANDA NOT CONFIGURED');const r=await fetch(this.restBase+path,{headers:{Authorization:`Bearer ${this.token}`,'Accept-Datetime-Format':'RFC3339'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(r.status===401?'OANDA AUTHENTICATION FAILED':`OANDA REQUEST FAILED (${r.status})`);return r.json() as Promise<any>}
  private normalize(raw:OandaPrice):NormalizedPrice{const bid=Number(raw.bids?.[0]?.price??raw.closeoutBid),ask=Number(raw.asks?.[0]?.price??raw.closeoutAsk);if(!Number.isFinite(bid)||!Number.isFinite(ask))throw new Error('OANDA PRICE UNAVAILABLE');return {instrument:'XAUUSD',bid,ask,mid:+((bid+ask)/2).toFixed(5),spread:+(ask-bid).toFixed(5),timestamp:raw.time,source:this.source,mode:this.mode,status:'LIVE'}}
  private async openStream(){this.abort=new AbortController();try{const r=await fetch(`${this.streamBase}/v3/accounts/${encodeURIComponent(this.account)}/pricing/stream?instruments=XAU_USD&snapshot=true`,{headers:{Authorization:`Bearer ${this.token}`},signal:this.abort.signal});if(!r.ok)throw new Error(r.status===401?'OANDA AUTHENTICATION FAILED':`OANDA STREAM FAILED (${r.status})`);this.connected=true;this.attempt=0;console.info('[OANDA] Connected XAU_USD');const reader=r.body!.getReader();const decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){if(!line.trim())continue;const raw=JSON.parse(line);if(raw.type==='HEARTBEAT')continue;const price=this.normalize(raw);this.latest=price;this.listeners.forEach(l=>l(price))}}}catch(e){if((e as Error).name==='AbortError')return;console.error('[OANDA]',e instanceof Error?e.message:e)}finally{this.abort=undefined;this.connected=false;if(this.isConfigured()){const delay=Math.min(30000,1000*2**this.attempt++);console.warn(`[OANDA] Reconnecting in ${delay}ms`);this.retry=setTimeout(()=>{this.retry=undefined;this.start()},delay)}}}
}
