import WebSocket from 'ws';
import type { MarketSnapshot, MarketStatus, MarketTimeframe, NormalizedCandle, NormalizedPrice } from '../../shared/types.js';
import { technicalLevels, type MarketDataProvider } from './market.js';

export const TWELVE_DATA_INTERVAL:Record<MarketTimeframe,string>={'5M':'5min','15M':'15min','1H':'1h','4H':'4h','1D':'1day'};
type CacheItem={expires:number,value?:unknown,promise?:Promise<unknown>};

export class TwelveDataMarketDataProvider implements MarketDataProvider {
  readonly source='TWELVE_DATA' as const;readonly mode='LIVE' as const;
  private readonly key=process.env.TWELVE_DATA_API_KEY?.trim()||'';private readonly pollMs=Math.max(15000,Number(process.env.TWELVE_DATA_POLL_INTERVAL_MS)||60000);
  private listeners=new Set<(p:NormalizedPrice)=>void>();private latest:NormalizedPrice|null=null;private status:MarketStatus='CONNECTING';private pollTimer?:NodeJS.Timeout;private ws?:WebSocket;private reconnectTimer?:NodeJS.Timeout;private attempt=0;private cache=new Map<string,CacheItem>();private stopped=true;private streamRejected=false;private priceInflight?:Promise<NormalizedPrice>;private requestCountToday=0;private requestDate=this.today();
  constructor(){console.info('[TWELVE DATA] Provider selected');console.info(`[TWELVE DATA] API key configured: ${this.key?'yes':'no'}`);console.info('[TWELVE DATA] XAUUSD symbol resolved: XAU/USD')}
  isConfigured(){return Boolean(this.key)}
  getStatus(){if(!this.isConfigured())return 'NOT_CONFIGURED' as const;if(this.status==='RATE_LIMITED'||this.status==='INVALID_API_KEY')return this.status;if(!this.latest)return this.status==='DISCONNECTED'?'UNAVAILABLE':this.status;const age=Date.now()-Date.parse(this.latest.receivedAt??this.latest.timestamp);if(age>this.pollMs*2)return 'STALE' as const;if(this.status==='DISCONNECTED'||this.status==='RECONNECTING')return 'CACHED' as const;return this.status}
  async getCurrentPrice(){if(this.latest)return {...this.latest,status:this.getStatus()};return this.refreshCurrentPrice()}
  refreshCurrentPrice(){if(this.priceInflight)return this.priceInflight;this.priceInflight=this.pollPrice().finally(()=>{this.priceInflight=undefined});return this.priceInflight}
  async getCandles(timeframe:MarketTimeframe,count:number,before?:string):Promise<NormalizedCandle[]>{const safe=Math.min(5000,Math.max(15,Math.floor(count)));const params=new URLSearchParams({symbol:'XAU/USD',interval:TWELVE_DATA_INTERVAL[timeframe],outputsize:String(safe),order:'ASC',timezone:'UTC'});if(before)params.set('end_date',before.replace('T',' ').replace('Z',''));const key=`candles:${timeframe}:${safe}:${before??'latest'}`;const ttl=before?3600000:timeframe==='5M'?60000:timeframe==='15M'?120000:300000;return this.cached(key,ttl,async()=>{console.info(`[TWELVE DATA] requesting XAU/USD ${TWELVE_DATA_INTERVAL[timeframe]}`);const {json}=await this.request(`/time_series?${params}`);if(!Array.isArray(json.values)){const error=this.apiError(json);console.error(`[TWELVE DATA] Candle request failed: ${error.message}`);throw error}const unique=new Map<number,NormalizedCandle>();for(const value of json.values){const time=this.utc(value.datetime);const stamp=Date.parse(time);const open=Number(value.open),high=Number(value.high),low=Number(value.low),close=Number(value.close);if(!Number.isFinite(stamp)||![open,high,low,close].every(Number.isFinite))continue;unique.set(stamp,{time,open,high,low,close,volume:Number.isFinite(Number(value.volume))?Number(value.volume):0,complete:true})}const bars=[...unique.entries()].sort(([a],[b])=>a-b).map(([,bar])=>bar);if(!bars.length)throw new Error('TWELVE DATA RETURNED NO VALID CANDLES');console.info(`[TWELVE DATA] received ${bars.length} candles`);console.debug('[TWELVE DATA] first candle:',bars[0]);console.debug('[TWELVE DATA] latest candle:',bars.at(-1));return bars})}
  async getLevels(timeframe:MarketTimeframe='1H'){return technicalLevels(await this.getCandles(timeframe,100),await this.getCandles('1D',20),timeframe,this.source,this.getStatus())}
  async getSnapshot():Promise<MarketSnapshot>{if(!this.isConfigured())return {price:null,levels:null,configured:false,mode:this.mode,status:'NOT_CONFIGURED',staleAfterMs:this.pollMs*2,message:'TWELVE DATA NOT CONFIGURED'};try{return {price:await this.getCurrentPrice(),levels:await this.getLevels(),configured:true,mode:this.mode,status:this.getStatus(),staleAfterMs:this.pollMs*2}}catch(e){return {price:this.latest,levels:null,configured:true,mode:this.mode,status:this.getStatus(),staleAfterMs:this.pollMs*2,message:e instanceof Error?e.message:'Twelve Data unavailable'}}}
  subscribeToPrice(listener:(p:NormalizedPrice)=>void){this.listeners.add(listener);if(this.latest)listener({...this.latest,status:this.getStatus()});return()=>this.listeners.delete(listener)}
  start(){if(!this.isConfigured()){this.status='NOT_CONFIGURED';return}if(!this.stopped)return;this.stopped=false;this.status='CONNECTING';this.connectStream()}
  stop(){this.stopped=true;this.ws?.close();this.ws=undefined;if(this.pollTimer)clearInterval(this.pollTimer);if(this.reconnectTimer)clearTimeout(this.reconnectTimer);this.pollTimer=undefined;this.reconnectTimer=undefined;this.status='DISCONNECTED'}
  private connectStream(){if(this.stopped||this.ws||this.streamRejected)return this.enablePolling();console.info('[TWELVE DATA] WebSocket supported: checking account access');const ws=new WebSocket(`wss://ws.twelvedata.com/v1/quotes/price?apikey=${encodeURIComponent(this.key)}`);this.ws=ws;const accessTimer=setTimeout(()=>{if(!this.latest)this.rejectStream(ws,'no fresh XAU/USD event on this account')},10000);ws.on('open',()=>ws.send(JSON.stringify({action:'subscribe',params:{symbols:'XAU/USD'}})));ws.on('message',raw=>{let event:any;try{event=JSON.parse(String(raw))}catch{return}if(event.event==='price'||event.type==='price'){const mid=Number(event.price);const providerTimestamp=event.timestamp?new Date(Number(event.timestamp)*1000).toISOString():null;if(!Number.isFinite(mid))return;if(providerTimestamp&&Date.now()-Date.parse(providerTimestamp)>this.pollMs*2){clearTimeout(accessTimer);this.rejectStream(ws,`stale provider event (${providerTimestamp})`);return}clearTimeout(accessTimer);if(this.status!=='CURRENT'){console.info('[TWELVE DATA] WebSocket supported: yes');console.info('[TWELVE DATA] Streaming connected')}this.status='CURRENT';this.attempt=0;const receivedAt=new Date().toISOString();const price:NormalizedPrice={instrument:'XAUUSD',bid:null,ask:null,mid,spread:null,timestamp:providerTimestamp??receivedAt,providerTimestamp,receivedAt,source:this.source,mode:this.mode,status:'CURRENT'};this.publish(price)}else if(event.status==='error'||event.code){const message=String(event.message??'');if(/api.?key|unauthorized/i.test(message))this.status='INVALID_API_KEY';else this.rejectStream(ws,message||'account does not support XAU/USD streaming');ws.close()}});ws.on('error',()=>{});ws.on('close',()=>{clearTimeout(accessTimer);this.ws=undefined;if(this.stopped)return;if(this.streamRejected||this.status==='INVALID_API_KEY')this.enablePolling();else{this.status='RECONNECTING';const delay=Math.min(30000,1000*2**this.attempt++);this.reconnectTimer=setTimeout(()=>{this.reconnectTimer=undefined;this.connectStream()},delay)}})}
  private enablePolling(){if(this.stopped||this.pollTimer||this.status==='INVALID_API_KEY')return;console.info(`[TWELVE DATA] REST polling enabled: ${this.pollMs}ms`);void this.refreshCurrentPrice().catch(()=>{});this.pollTimer=setInterval(()=>void this.refreshCurrentPrice().catch(()=>{}),this.pollMs)}
  private async pollPrice(){const endpoint='/price?symbol=XAU%2FUSD';this.rollRequestCount();console.info('[TWELVE DATA] XAUUSD refresh started');console.info('[TWELVE DATA] symbol: XAU/USD');console.info(`[TWELVE DATA] endpoint: https://api.twelvedata.com${endpoint}`);console.info(`[TWELVE DATA] request count today: ${++this.requestCountToday}`);try{const {json,status}=await this.request(endpoint);const mid=Number(json.price);if(!Number.isFinite(mid))throw this.apiError(json);const receivedAt=new Date().toISOString();this.status='CURRENT';const price:NormalizedPrice={instrument:'XAUUSD',bid:null,ask:null,mid,spread:null,timestamp:receivedAt,providerTimestamp:null,receivedAt,source:this.source,mode:this.mode,status:'CURRENT'};console.info(`[TWELVE DATA] HTTP status: ${status}`);console.info(`[TWELVE DATA] returned price: ${mid}`);console.info('[TWELVE DATA] provider timestamp: unavailable on /price response');console.info(`[TWELVE DATA] received at: ${receivedAt}`);this.publish(price);console.info('[TWELVE DATA] cache updated');return price}catch(e){if(this.status!=='RATE_LIMITED'&&this.status!=='INVALID_API_KEY')this.status=this.latest?'CACHED':'UNAVAILABLE';console.error(`[TWELVE DATA] refresh failed: ${e instanceof Error?e.message:e}`);throw e}}
  private publish(price:NormalizedPrice){this.latest=price;this.listeners.forEach(l=>l(price))}
  private async request(path:string){if(!this.isConfigured())throw new Error('TWELVE DATA NOT CONFIGURED');const r=await fetch(`https://api.twelvedata.com${path}`,{headers:{Authorization:`apikey ${this.key}`},signal:AbortSignal.timeout(12000)});const json=await r.json() as any;if(r.status===429||json.code===429){this.status='RATE_LIMITED';throw new Error('TWELVE DATA RATE LIMITED')}if(r.status===401||json.code===401){this.status='INVALID_API_KEY';throw new Error('TWELVE DATA INVALID API KEY')}if(!r.ok||json.status==='error')throw this.apiError(json);return {json,status:r.status}}
  private apiError(json:any){const message=String(json?.message??'TWELVE DATA REQUEST FAILED');if(/api.?key|invalid key/i.test(message))this.status='INVALID_API_KEY';if(/credit|rate limit/i.test(message))this.status='RATE_LIMITED';return new Error(message)}
  private rejectStream(ws:WebSocket,reason:string){if(this.streamRejected)return;this.streamRejected=true;console.warn(`[TWELVE DATA] WebSocket rejected for current pricing: ${reason}; using API polling`);ws.close()}
  private today(){return new Date().toISOString().slice(0,10)}
  private rollRequestCount(){const today=this.today();if(today!==this.requestDate){this.requestDate=today;this.requestCountToday=0}}
  private async cached<T>(key:string,ttl:number,load:()=>Promise<T>):Promise<T>{const now=Date.now();const item=this.cache.get(key);if(item?.value&&item.expires>now)return item.value as T;if(item?.promise)return item.promise as Promise<T>;const promise=load().then(value=>{this.cache.set(key,{value,expires:Date.now()+ttl});return value}).catch(e=>{this.cache.delete(key);throw e});this.cache.set(key,{expires:0,promise});return promise}
  private utc(value:string){return value.includes('T')?new Date(value).toISOString():new Date(`${value.replace(' ','T')}Z`).toISOString()}
}
